#!/bin/bash

export PGI=/opt/pgi
export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH
export MANPATH=$MANPATH:/opt/pgi/linux86-64/19.10/man
export LM_LICENSE_FILE=$LM_LICENSE_FILE:/opt/pgi/license.dat

export PATH=$PATH:/usr/local/cuda-10.1/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.1/lib64

export F90=pgf90
export F90FLAGS="-O1 -acc -ta=tesla,cc60 -Minfo=all"
export LDFLAGS="-acc -ta=tesla,cc60"

# *** INCLUDING THESE STOPS ASYNC exe from working!!! ***

export PGI_ACC_TIME=1
export LD_LIBRARY_PATH=/opt/pgi/linux86-64-llvm/19.10/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# To turn on PGI profile info:
# pgprof --print-gpu-trace ./traadv_gpu.exe

# To control which GPU to use (P400 or P4000):
# $CUDA_VISIBLE_DEVICES="0" ./traadv.exe

# Device 0 - P4000
# Device 1 - P400

